"""The board — `tasks/README.md`, regenerated from the database.

Task state lives in SQLite so that bookkeeping does not collide with the work
being tracked. The cost of that choice is that state is machine-local: a factory
box that dies takes its history with it. This file is the mitigation — a lossy
but durable summary, written into git after every merge, so "what got built and
what is stuck" survives the database.

Generated. Edits here are overwritten on the next sync.
"""

from __future__ import annotations

from pathlib import Path

from db import Factory

MARK = {
    "done": "✅",
    "blocked": "⛔",
    "awaiting_human": "🔒",
    "needs_work": "↻",
    "running": "▶",
    "gating": "▶",
    "reviewing": "▶",
    "merging": "▶",
    "ready": "·",
}


def _spend(fac: Factory) -> str:
    """Billed and notional spend, never added together.

    Under subscription auth the CLI reports a cost computed from token counts
    and list prices, but nothing was charged. A single total mixing the two is
    a number that describes neither.
    """
    split = fac.cost_split()
    if split["notional"] and split["billed"]:
        return f"${split['billed']:.2f} billed + ${split['notional']:.2f} notional"
    if split["notional"]:
        return f"${split['notional']:.2f} notional (subscription)"
    return f"${split['billed']:.2f} billed"


def render(fac: Factory, repo: Path) -> str:
    tasks = fac.all_tasks()
    costs = fac.cost_by_task()
    done = sum(1 for t in tasks if t.status == "done")
    blocked = [t for t in tasks if t.status in ("blocked", "awaiting_human")]

    lines = [
        "# Task queue",
        "",
        "<!-- Generated by `factory/run.py sync`. Do not edit — the source of",
        "     truth is the packet frontmatter in this directory plus the state",
        "     database at `.factory/factory.db`. -->",
        "",
        f"**{done}/{len(tasks)} merged** · {_spend(fac)}",
        "",
        "| | ID | Tier | Review | Goal | Status | Att. | Cost |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for t in tasks:
        cost = costs.get(t.id, {})
        total = cost.get("impl", 0.0) + cost.get("review", 0.0)
        # Deliberately no merge sha here. The board is folded into the very
        # commit it would name, so it can never be self-consistent; the sha
        # lives in `tasks.merged_sha`, which is what a revert needs anyway.
        status = t.status
        lines.append(
            f"| {MARK.get(t.status, '?')} | `{t.id}` | {t.model} | {t.reviewer} | "
            f"{t.goal[:56]} | {status} | {t.attempts} | "
            f"{f'${total:.2f}' if total else '—'} |"
        )

    if blocked:
        lines += ["", "## Needs attention", ""]
        for t in blocked:
            what = (
                "held for human approval" if t.status == "awaiting_human" else "blocked"
            )
            lines.append(
                f"- **`{t.id}`** — {what}: {t.blocked_reason or 'no reason recorded'}"
            )
            if t.status == "awaiting_human":
                lines.append(f"  - `./factory/run.py approve {t.id}`")
            lines.append(
                f"  - `./factory/run.py reset {t.id}` to discard it and start over"
            )

    ready = [t for t in tasks if t.status in ("ready", "needs_work")]
    if ready:
        lines += [
            "",
            "## Next",
            "",
            "Dependency-resolved order — `./factory/run.py plan` for the live view.",
            "",
        ]
        for t in fac.runnable_order()[:8]:
            gate = " · **human gate**" if t.gate == "human" else ""
            lines.append(f"1. `{t.id}` {t.goal[:60]}{gate}")

    lines += [
        "",
        "---",
        "",
        "Packets are the `*.md` files here; each is self-contained and pinned to the",
        "spec commit it was cut from. `tasks/supplied/<ID>/` holds files the harness",
        "plants into the worktree before the implementer runs — tests it may not edit.",
        "",
        "```",
        "./factory/run.py sync     register packets",
        "./factory/run.py plan     resolved order, nothing invoked",
        "./factory/run.py run      drain the queue",
        "```",
        "",
    ]
    return "\n".join(lines)


def write(fac: Factory, path: Path, repo: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(fac, repo), encoding="utf-8")
